version: '3'

services :
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    command: "node server.js"
    ports:
      - "4000:4000"
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    command: "npm start"
    ports:
      - "3000:3000"
    depends_on:
      - "server"
  